config/routes.rb
Rails.application.routes.draw do
  root 'reports#index'
  resources :reports

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/report.rb
class Report < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @reports = Report.all
  end

  def new
    @report = Report.new
  end

  def create
    report = Report.new(report_params)
    if report.save
      redirect_to "/"
    end
  end

  private
  def report_params
    params.require(:report).permit(:evaluation_id, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Modal</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reports/_form.html.erb
<%= form_for Report.new do |f| %>
  <%= f.number_field :evaluation_id %>
  <%= f.text_field :body %>
  <%= f.submit "send" %>
<% end %>

app/views/reports/index.html.erb
<h1>Reports#index</h1>
<p>Find me in app/views/reports/index.html.erb</p>
<%= link_to 'New Report', reports_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'}  %>

<div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>

<% @reports.each do |r| %>
    <%= r.evaluation_id %>
    <%= r.body %>
    <br>
<% end %>

app/views/reports/index.js.erb
$("#modal-window").html("<%= escape_javascript(render 'form') %>");